import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center`}
      >
        <div className="flex flex-col max-w-[1200px] w-full">
          <nav className="flex justify-between p-4 ">
            <div>
              <Link href={"/"}>LeChuck</Link>
            </div>
            <div className="flex gap-2">
              <Link href={"/posts/url-search-params"}>example</Link>
              <div>github</div>
              <div>theme</div>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
