openapi: 3.0.0
info:
  version: 1.0.0
  title: blog
  description: 개인 블로그
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LeChuckbb/blog/1.0.0
  - description: blog
    url: http://localhost:8000/api/v1
tags:
  - name: post
    description: about posts
paths:
  /posts:
    get:
      tags:
        - post
      summary: 모든 게시글 가져오기
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: Invalid status value
        "403":
          description: Unknown
    post:
      tags:
        - post
      summary: 게시글 작성하기
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object

  /posts/{id}:
    get:
      tags:
        - post
      summary: ID로 게시글 가져오기 - 게시글 상세보기 (working)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
    patch:
      tags:
        - post
      summary: ID로 게시글 일부 수정하기 (working)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
    delete:
      tags:
        - post
      summary: ID로 게시글 삭제하기 (working)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK

  /posts/findByPage:
    get:
      tags:
        - post
      summary: 페이지 단위로 가져오기 for infinite scroll. ?page= (working)
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

components:
  schemas:
    Post:
      type: object
      properties:
        _id:
          type: string
        image:
          type: string
        title:
          type: string
        subTitle:
          type: string
        date:
          type: string
        tags:
          type: array
          items:
            type: string
